import collections
CAPTION = "Applesauce"


SCREEN_SIZE = collections.namedtuple('Size', 'width height')(800, 600)

ENEMY_MAX_V = 4

TIME_IN_RANDOM_DIR = 100

TIME_UNTIL_LOST = 100
TIME_UNTIL_OFFICER_LOST = TIME_UNTIL_LOST

OFFICER_VIEW_DISTANCE = 300
OFFICER_ALERT_DISTANCE = 100

BOOMBOX_RADIUS = 150

TURKEY_SPEED_MODIFIER = 0.75

HUD_FONT_SIZE = 32

FLYER_RADIUS = 500
