import collections
CAPTION = "Applesauce"


SCREEN_SIZE = collections.namedtuple('Size', 'width height')(800, 600)

ENEMY_MAX_V_1 = 2
ENEMY_MAX_V_2 = 3

OFFICER_MAX_V_1 = 3.5
OFFICER_MAX_V_2 = 4.5

TIME_IN_RANDOM_DIR = 100
TIME_IN_RANDOM_DIR_VARIATION = 100

TIME_UNTIL_LOST = 100
TIME_UNTIL_OFFICER_LOST = TIME_UNTIL_LOST

OFFICER_VIEW_DISTANCE = 300
OFFICER_ALERT_DISTANCE = 100

BOOMBOX_RADIUS = 150

TURKEY_SPEED_MODIFIER = 0.75

HUD_FONT_SIZE = 32

FLYER_RADIUS = 500
